name: CI

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GAME_VERSION: EMERALD
      GAME_REVISION: 0
      GAME_LANGUAGE: ENGLISH
      MODERN: 0
      COMPARE: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare symbols directory
        if: ${{ github.event_name == 'push' }}
        run: |
          mkdir -p symbols

      - name: Checkout agbcc
        uses: actions/checkout@v4
        with:
          path: agbcc
          repository: pret/agbcc
          ref: 6a3d5c6

      - name: Install binutils
        run: |
          sudo apt install gcc-arm-none-eabi binutils-arm-none-eabi libpng-dev

      - name: Install agbcc
        run: |
          ./build.sh
          ./install.sh ../
        working-directory: agbcc

      - name: Compare
        run: make -j$(nproc) all syms

      - name: Modern
        env:
          MODERN: 1
          COMPARE: 0
        run: make -j$(nproc) all

      - name: Move symfiles
        if: ${{ github.event_name == 'push' }}
        run: |
          cp -v *.sym symbols/
          echo "SYMBOLS_COMMIT_MSG=$(git log --format=%s ${GITHUB_SHA})" >> $GITHUB_ENV

      - name: Update symfiles
        if: ${{ github.event_name == 'push' }}
        uses: EndBug/add-and-commit@v9
        with:
          branch: symbols
          cwd: "./symbols"
          add: "*.sym"
          message: ${{ env.SYMBOLS_COMMIT_MSG }}
